version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm install
      - zip -r lambda.zip index.js node_modules
  post_build:
    commands:
      - aws s3 cp lambda.zip s3://codepipeline-ap-south-1-600127048539/lambda.zip
artifacts:
  files:
    - lambda.zip
