version: 0.2

phases:
  build:
    commands:
      - echo "Fetching latest Lambda package from S3..."
      - aws s3 cp s3://codepipeline-ap-south-1-600127048539/lambda.zip .
      - echo "Deploying to AWS Lambda..."
      - aws lambda update-function-code --function-name MyLambdaFunction --s3-bucket my-lambda-artifacts --s3-key lambda.zip
      - echo "Deployment successful!"
